CREATE TABLE TEAM (
  TeamID INT,
  TeamName VARCHAR(255) NOT NULL,
  PRIMARY KEY (TeamID)
);

CREATE TABLE USER (
  UserID INT PRIMARY KEY,
  TeamID INT,
  UserName VARCHAR(255) NOT NULL,
  PW VARCHAR(255) NOT NULL,
  FOREIGN KEY (TeamID) REFERENCES TEAM (TeamID)
);



CREATE TABLE TOKEN (
  TokenID INT PRIMARY KEY,
  TokenValue VARCHAR(255) NOT NULL,
  TokenType VARCHAR(255)
);

CREATE TABLE UserToToken (
  UserID INT,
  TokenID INT,
  FOREIGN KEY (UserID) REFERENCES USER(UserID),
  FOREIGN KEY (TokenID) REFERENCES TOKEN(TokenID),
  PRIMARY KEY (UserID, TokenID)
);

INSERT INTO TEAM VALUES(1,"Investment Team 1");
INSERT INTO USER VALUES(1,1,"TaeheeKim","MyPassword");