version: '3.1'

services:

  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: example
      MARIADB_USER_NAME: testuser
      MARIADB_USER_PASSWORD: pass

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080